config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :submits
  end
  resources :levels do
    resources :tests
  end
  resources :levels do
    resources :attachments
  end
  resources :programs do
    resources :levels
  end
  root 'page#home'
  get 'page/instruction'
  devise_for :admins
  devise_for :users

end

app/models/program.rb
class Program < ActiveRecord::Base
	belongs_to :user
	has_many :levels
    before_save :capitalize_language
    before_save :capitalize_description


	def capitalize_language
      self.language = self.language.split.collect(&:capitalize).join(' ') if self.language && !self.language.blank?
    end

	def capitalize_description
      self.description = self.description.split.collect(&:capitalize).join(' ') if self.description && !self.description.blank?
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to programs_url }
        flash[:success] = 'Program was successfully created.' 
        format.json { render :show, status: :created, location: programs_url}
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to sprograms_url }
        flash[:success] ='Program was successfully updated.' 
        format.json { render :show, status: :ok, location: programs_url }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url}
      flash[:success] ='Program was successfully destroyed.'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:language, :description)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.haml
.left
  = form_for(@program,html: { multipart: true, class: "form-horizontal" }) do |f|
    - if @program.errors.any?
      #error_explanation
        %h2
          = pluralize(@program.errors.count, "error")
          prohibited this program from being saved:
        %ul
          - @program.errors.full_messages.each do |message|
            %li= message
    .form-group
      .col-md-3
        = f.label :language
        %br
          = f.text_field :language,placeholder: 'programming language',class: 'form-control'
    .form-group
      .col-md-3
        = f.label :description
        %br
          = f.text_area :description,placeholder: 'description',class: 'form-control'
    .form-group
      = f.submit class: 'btn btn-primary'
:javascript
  $(document).ready(function () {
    $("#new_program").validate({
      debug: false,
      rules: {
        "program[language]": { required: true},
        "program[description]": { required: true}
        },
        messages: {
        "program[language]": "Please enter the language.",
        "program[description]": "Please enter the description."
        }
      });
  });

app/views/programs/edit.html.haml
%h1 Edit Program
= render 'form'
= link_to 'Back', programs_path,class: 'btn btn-success'
:javascript
  $(document).ready(function () {
    $(".form-horizontal").validate({
      debug: false,
      rules: {
        "program[language]": { required: true},
        "program[description]": { required: true}
        },
        messages: {
        "program[language]": "Please enter the language.",
        "program[description]": "Please enter the description."
        }
      });
  });

app/views/programs/index.html.haml
%p#notice= notice
%h2{:style => "font-weight: bold;"} Programs:
%br
  - if admin_signed_in?
    = link_to 'Add Program', new_program_path,class: 'btn btn-success'
  - if user_signed_in?
    = link_to 'Back',page_instruction_path,class: 'btn btn-success'

  %table.table.table-hover
    %thead

      %tr
        %th Language
        %th Description
        %th{:colspan => "3"}
    %tbody
      - @programs.each do |program|
        %tr
          %td{:style => "font-weight: bold;"}= link_to program.language,program_levels_path(program)
          %td= program.description
          - if admin_signed_in?
            %td= link_to 'Edit', edit_program_path(program),class: 'btn btn-warning'
            %td= link_to 'Delete', program, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger'
  %br

app/views/programs/new.html.haml
.left
  %h1 New Program
  = render 'form'
  = link_to 'Back', programs_path, class: 'btn btn-success'