config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :submits
  end
  resources :levels do
    resources :tests
  end
  resources :levels do
    resources :attachments
  end
  resources :programs do
    resources :levels
  end
  root 'page#home'
  get 'page/instruction'
  devise_for :admins
  devise_for :users

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :level
	mount_uploader :document, DocumentUploader
	 before_save :capitalize_name

	def capitalize_name
      self.name = self.name.split.collect(&:capitalize).join(' ') if self.name && !self.name.blank?
    end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @level = Level.find(params[:level_id])
    @attachments = @level.attachments
    if params[:start_date]
      @user = current_user
      @admin = Admin.last
      StartTrainingAdmin.start_training_email(@admin, @level,@user).deliver_now
      StartTrainingUser.start_training_email(@user, @level).deliver_now
      @level.update(start_date: Time.now)
      @level.update(end_date: (@level.start_date + @level.duration.to_i.days))
      redirect_to level_attachments_path(@level)
      flash[:success] = "The #{@level.name} training has been started."
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @level = Level.find(params[:level_id])
    @attachment = @level.attachments.find(params[:id])
  end

  # GET /attachments/new
  def new
    @level = Level.find(params[:level_id])
    @attachment = @level.attachments.build
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
   @level = Level.find(params[:level_id])
    @attachment = @level.attachments.create(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to level_attachments_path(@level)}
        flash[:success] = 'Attachment was successfully created.' 
        format.json { render :show, status: :created, location: level_attachments_path(@level) }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    @level = Level.find(params[:level_id])
    @attachment = @level.attachments.find(params[:id])
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to level_attachments_path(@level)}
        flash[:success] = 'Attachment was successfully updated.' 
        format.json { render :show, status: :ok, location: level_attachments_path(@level) }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @level = Level.find(params[:level_id])
    @attachment = @level.attachments.find(params[:id])
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to level_attachments_url}
      flash[:success] = 'Attachment was successfully destroyed.' 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
     @level = Level.find(params[:level_id])
     @attachment = @level.attachments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:document,:name,:level_id)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.haml
= form_for([@attachment.level,@attachment],html: { multipart: true, class: "form-horizontal" }) do |f|
  - if @attachment.errors.any?
    #error_explanation
      %h2
        = pluralize(@attachment.errors.count, "error")
        prohibited this attachment from being saved:
      %ul
        - @attachment.errors.full_messages.each do |message|
          %li= message
  .form-group
    .col-md-3
      = f.label :name
      %br
        = f.text_field :name,placeholder: 'document name',class: 'form-control'
  .form-group
    .col-md-3
      = f.label :document
      %br
        = f.file_field :document
  .form-field
    = f.submit class: 'btn btn-primary left'
    
:javascript
  $(document).ready(function () {
    $("#new_attachment").validate({
      debug: false,
      rules: {
        "attachment[name]": { required: true},
        "attachment[document]": { required: true},
        },
        messages: {
        "attachment[name]": "Please enter the Name.",
        "attachment[document]": "Please choose the Document.",
        }
      });
  });

app/views/attachments/edit.html.haml
%h1 Edit Attachment
= render 'form'
= link_to 'Back', level_attachments_path(@attachment.level),class: 'btn btn-success'
:javascript
  $(document).ready(function () {
    $(".form-horizontal").validate({
      debug: false,
      rules: {
        "attachment[name]": { required: true},
        "attachment[document]": { required: true},
        },
        messages: {
        "attachment[name]": "Please enter the Name.",
        "attachment[document]": "Please choose the Document.",
        }
      });
  });

app/views/attachments/index.html.haml
%p#notice= notice
%h1 List of Materials:
- if admin_signed_in?
  %td= link_to 'Add Attachment', new_level_attachment_path,class: 'btn btn-success'
  |
= link_to 'Back', program_levels_path(@level.program),class: 'btn btn-success'
%table.table.table-hover
  %thead
    %tr
      %th Document Name
      %th Download Document
      %th{:colspan => "3"}
  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.name
        %td= link_to "View Document", attachment.document_url,class: 'btn btn-primary'
        - if admin_signed_in?
          %td= link_to 'Edit', edit_level_attachment_path(attachment.level,attachment),class: 'btn btn-warning'
          %td= link_to 'Destroy', [attachment.level,attachment], method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-danger'

app/views/attachments/new.html.haml
%h1 New Attachment
= render 'form'
= link_to 'Back', program_levels_path(@level.program),class: 'btn btn-success'