config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :submits
  end
  resources :levels do
    resources :tests
  end
  resources :levels do
    resources :attachments
  end
  resources :programs do
    resources :levels
  end
  root 'page#home'
  get 'page/instruction'
  devise_for :admins
  devise_for :users

end

app/views/page/home.html.haml
- if user_signed_in?
  %h1{:style => "text-align: center;margin-top: 150px;font-weight: bold;"}
    = current_user.name
    Welcome to RubyEffect!
  %p{:style => "text-align: center;font-weight: bold;"}
    Here we will take you to #{link_to 'Training Session.',page_instruction_path}
- elsif admin_signed_in?
  %h1{:style => "text-align: center;margin-top: 150px;font-weight: bold;"}
    = current_admin.name
    Welcome to RubyEffect!
  %p{:style => "text-align: center;font-weight: bold;"}
    Here is #{link_to 'Training Session.',programs_path}
- else
  .relogo
    = image_tag("relogo.png", :alt => "RE Logo")
    %h1 Training Management

app/views/page/instruction.html.haml
%h3{:style => "text-align: center;font-weight: bold;margin-top: 30px;"} RE Learning Program
%h4{:style => "font-weight: bold;margin-left: 10px;"} Training Instruction
.left
  %p 1.The training period is for 3 months(90 days).In this period you will learn about RUBY ON RAILS and its related programming languages.
  %p 2.The training is in RUBY ON RAILS programming languages divided into different modules.
  %p 3.Each module has 3 levels i.e Basic,moderate and high.
  %p 4.Basic level contains basics of each module or programmig language.Moderate level contains the work flow of each module or programming language and High level contains when and where to use the programming language.
  %p 5.At the end of each level,you will be having test.
  %p 6.The pattern of test can be a programming question or Build an Application
  %p 7.When you click on submit,you need to attach the code for the questions asked in test
  %p 7.The test feedback will be send to your email.
  %p 8.Based on the feedback and test score your performance review will be taken.
  %p{:style => "font-weight: bold;"} So lets start the training to make your programming skill more efficient.
  
%p{:style => "text-align:center;"}= link_to 'Next',programs_path,class: 'btn btn-primary'