config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :submits
  end
  resources :levels do
    resources :tests
  end
  resources :levels do
    resources :attachments
  end
  resources :programs do
    resources :levels
  end
  root 'page#home'
  get 'page/instruction'
  devise_for :admins
  devise_for :users

end

app/models/level.rb
class Level < ActiveRecord::Base
	belongs_to :program
	has_many :attachments
	has_many :tests
	before_save :capitalize_name
	validates_numericality_of :duration, :allow_nil => true

	def capitalize_name
      self.name = self.name.split.collect(&:capitalize).join(' ') if self.name && !self.name.blank?
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @program = Program.find(params[:program_id])
    @levels = @program.levels
    
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
    @program = Program.find(params[:program_id])
    @level = @program.levels.find(params[:id])
  end

  # GET /levels/new
  def new
    @program = Program.find(params[:program_id])
    @level = @program.levels.build
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @program = Program.find(params[:program_id])
    @level = @program.levels.build(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to program_levels_path(@program)}
        flash[:success] = 'Level was successfully created.' 
        format.json { render :show, status: :created, location: program_levels_path(@program) }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    @program = Program.find(params[:program_id])
    @level = @program.levels.find(params[:id])
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to program_levels_path(@program)}
        flash[:success] = 'Level was successfully updated.' 
        format.json { render :show, status: :ok, location: program_levels_path(@program) }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @program = Program.find(params[:program_id])
    @level = @program.levels.find(params[:id]) 
    @level.destroy
    respond_to do |format|
      format.html { redirect_to program_levels_url}
      flash[:success] = 'Level was successfully destroyed.' 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
     @program = Program.find(params[:program_id])
     @level = @program.levels.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :duration,:program_id,:start_date,:end_date)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.haml
.left
  = form_for([@level.program,@level],html: { multipart: true, class: "form-horizontal" }) do |f|
    - if @level.errors.any?
      #error_explanation
        %h2
          = pluralize(@level.errors.count, "error")
          prohibited this level from being saved:
        %ul
          - @level.errors.full_messages.each do |message|
            %li= message
    .form-group
      .col-md-3
        = f.label :name
        %br
          = f.text_field :name,placeholder: 'level name',class: 'form-control'
    .form-group
      .col-md-3
        = f.label :duration,'Duration(days)'
        %br
          = f.text_field :duration,placeholder: 'level duration',class: 'form-control'
    .form-group
      = f.submit class: 'btn btn-primary'
:javascript
  $(document).ready(function () {
    $("#new_level").validate({
      debug: false,
      rules: {
        "level[name]": { required: true},
        "level[duration]": { required: true}
        },
        messages: {
        "level[name]": "Please enter the name.",
        "level[duration]": "Please enter the duration."
        }
      });
  });

app/views/levels/edit.html.haml
%h1 Edit Level
= render 'form'
= link_to 'Back', program_levels_path(@level.program),class: 'btn btn-success'
:javascript
  $(document).ready(function () {
    $(".form-horizontal").validate({
      debug: false,
      rules: {
        "level[name]": { required: true},
        "level[duration]": { required: true}
        },
        messages: {
        "level[name]": "Please enter the name.",
        "level[duration]": "Please enter the duration."
        }
      });
  });

app/views/levels/index.html.haml
%p#notice= notice
%h2{:style => "font-weight: bold;"} Levels:
%br
  - if admin_signed_in?
    = link_to 'Add Level', new_program_level_path,class: 'btn btn-success'
    |
  = link_to 'Back',programs_path,class: 'btn btn-success'
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Duration(days)
        %th Attachments
        %th Test
        - if admin_signed_in?
          %th{:style => "text-align: center;"} Action
        %th{:colspan => "3"}
    %tbody
      - @levels.each do |level|
        %tr
          %td{:style => "font-weight: bold;"}= level.name
          %td{:style => "font-weight: bold;"}= level.duration
          - if user_signed_in?
            - if level.start_date.present?
              %td= link_to 'View Materials',level_attachments_path(level),class: 'btn btn-primary'
            - else
              %td= link_to 'Start Training',level_attachments_path(level,start_date: true),class: 'btn btn-primary'
          - if user_signed_in?
            - if level.end_date.present?
              - if (Time.now > level.end_date)
                %td= link_to 'Start Test',level_tests_path(level),class: 'btn btn-primary'
          - if admin_signed_in?
            %td= link_to 'Attachments',level_attachments_path(level),class: 'btn btn-primary'
            %td
              = link_to 'Test',level_tests_path(level),class: 'btn btn-primary'
              %td= link_to 'Edit', edit_program_level_path(level.program,level),class: 'btn btn-warning'
              %td= link_to 'Destroy',[level.program,level], method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger'
  %br

app/views/levels/new.html.haml
.left
  %h1 New Level
  = render 'form'
  = link_to 'Back', program_levels_path(@level.program),class: 'btn btn-success'